- name: Deploy Bacula Director
  hosts: bacula_director
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Preseed dbconfig-common to not install database
      debconf:
        name: bacula-director-pgsql
        question: bacula-director-pgsql/dbconfig-install
        vtype: boolean
        value: false
      become: true
    - name: Install Bacula Director (non-interactive)
      apt:
        name:
          - bacula-director-pgsql
          - bacula-console
        state: present
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Deploy bacula-dir.conf from template
      template:
        src: ../templates/bacula-dir.conf.j2
        dest: /etc/bacula/bacula-dir.conf
        owner: bacula
        group: bacula
        mode: '0640'
      notify: restart bacula-director
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
    - name: Ensure Bacula Director is running
      service:
        name: bacula-director
        state: started
        enabled: yes
    - name: Deploy bconsole.conf from template
      ansible.builtin.template:
        src: ../templates/bconsole.conf.j2
        dest: /etc/bacula/bconsole.conf
        owner: root
        group: bacula
        mode: '0640'
  handlers:
    - name: restart bacula-director
      service:
        name: bacula-director
        state: restarted